# Generated by Django 6.0.7 on 2026-08-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPlane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name of the archiver for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique plane name.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "zstack",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Vertical stack label shared by aligned planes. Blank = standalone/interior.",
                        max_length=100,
                    ),
                ),
                (
                    "elevation",
                    models.IntegerField(
                        default=0,
                        help_text="Layer position within the zstack (meaningful only when zstack is set).",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description shown on the web map.",
                        max_length=1000,
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who archived this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the plane.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned tiles are never moved by auto-placement or +map/reflow.",
                    ),
                ),
                (
                    "terrain",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized base terrain (resolved from the room's terrain_tags set).",
                        max_length=64,
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized room name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plane",
                    models.ForeignKey(
                        help_text="The plane this tile is placed on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="evennia_maps.mapplane",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="The room placed at this tile. A room may hold only one tile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mapplane",
            constraint=models.UniqueConstraint(
                condition=models.Q(("zstack", ""), _negated=True),
                fields=("zstack", "elevation"),
                name="evennia_maps_one_plane_per_elevation",
            ),
        ),
        migrations.AddIndex(
            model_name="roomtile",
            index=models.Index(
                fields=["plane", "x", "y"], name="evennia_map_plane_i_1ad5b9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtile",
            unique_together={("plane", "x", "y"), ("room",)},
        ),
    ]
