# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, an0n-b1nary. See LICENSE for full terms.
# Generated by Django 6.0.7 on 2026-10-05 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by_name', models.CharField(blank=True, help_text='Denormalized name of the archiver for display after deletion.', max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('scene_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('set_by_name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('stat_key', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('once', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_reason', models.CharField(blank=True, max_length=100)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='The character who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('scene_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('stat', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_display', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('outcome_key', models.CharField(max_length=100)),
                ('outcome_degree', models.SmallIntegerField()),
                ('is_success', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('alternative', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='evennia_rp_contest.challenge')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RoomSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.objectdb')),
            ],
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('room', 'number'), name='rp_contest_room_number'),
        ),
        migrations.AddConstraint(
            model_name='checkrecord',
            constraint=models.UniqueConstraint(fields=('challenge', 'character', 'attempt_no'), name='rp_contest_actor_attempt'),
        ),
    ]
