# Generated by Django 6.0.3 on 2026-06-15 05:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name of the archiver for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional scene title.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional scene summary/description."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("pose_private", "Pose-Private"),
                            ("view_private", "View-Private"),
                        ],
                        default="public",
                        max_length=13,
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized room name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the first pose transitions status to active.",
                        null=True,
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Set when the scene is closed.", null=True
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who archived this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The character who opened this scene.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evennia_created_scenes",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="The room where this scene takes place.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evennia_scenes",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized author name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full pose/say/emit/ooc/system text."
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("pose", "Pose"),
                            ("emit", "Emit"),
                            ("say", "Say"),
                            ("ooc", "OOC"),
                            ("web_ooc", "Web OOC"),
                            ("dice", "Dice"),
                            ("combat", "Combat"),
                            ("system", "System"),
                        ],
                        default="pose",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag for individual entries.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Explicit ordering within a scene."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who created this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="evennia_scenes.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SceneParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the character leaves or the scene closes.",
                        null=True,
                    ),
                ),
                ("pose_count", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False if the character has left the scene.",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("participant", "Participant"),
                            ("observer", "Observer"),
                        ],
                        default="participant",
                        max_length=12,
                    ),
                ),
                (
                    "is_invited",
                    models.BooleanField(
                        default=False,
                        help_text="True if explicitly invited to pose in POSE_PRIVATE or VIEW_PRIVATE scenes.",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evennia_scene_participations",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="evennia_scenes.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="LogEntryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented per parent object."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full snapshot of the content at this version."
                    ),
                ),
                (
                    "editor_name",
                    models.CharField(
                        help_text="Denormalized name of the editor for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_rollback",
                    models.BooleanField(
                        default=False,
                        help_text="True if this version was created by a rollback operation.",
                    ),
                ),
                (
                    "rolled_back_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If is_rollback, the version number that was restored.",
                        null=True,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="The character who made this edit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="evennia_scenes.logentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "abstract": False,
                "unique_together": {("parent", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(
                fields=["status", "created_at"], name="evennia_sce_status_cd3742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["scene", "created_at"], name="evennia_sce_scene_i_abed64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sceneparticipant",
            unique_together={("scene", "character")},
        ),
    ]
