# Generated by Django 6.0

from django.db import migrations, models


def assign_scene_numbers(apps, schema_editor):
    Scene = apps.get_model("evennia_scenes", "Scene")
    manager = getattr(Scene, "all_objects", None) or Scene._default_manager
    for number, scene in enumerate(manager.using(schema_editor.connection.alias).order_by("pk"), start=1):
        scene.scene_number = number
        scene.save(using=schema_editor.connection.alias, update_fields=["scene_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("evennia_scenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="scene_number",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Stable public number used in player-facing scene commands.",
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(assign_scene_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="scene",
            name="scene_number",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Stable public number used in player-facing scene commands.",
                unique=True,
            ),
        ),
    ]
