# Generated by Django 6.0.3 on 2026-06-07 16:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "board_type",
                    models.CharField(
                        choices=[("ooc", "OOC"), ("ic", "IC")],
                        default="ooc",
                        max_length=3,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in +bb listing. Lower numbers appear first.",
                    ),
                ),
                (
                    "is_read_only",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only staff (BOARDS_STAFF_LOCK permission) can post.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name of the archiver for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "post_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented per board. Used for +bb Board/1 addressing."
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized author name for display after character deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "xp_flagged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set by the anti-gaming sweep (integrations/xp.py) when this post looks like cutscene spam. Flagged posts are excluded from XP awards until staff review and clear the flag.",
                    ),
                ),
                (
                    "xp_flag_reason",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated reason stored by the anti-gaming sweep.",
                        max_length=500,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who archived this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who created this post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="evennia_boards.board",
                    ),
                ),
                (
                    "parent_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this post is a reply to another post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="evennia_boards.post",
                    ),
                ),
            ],
            options={
                "ordering": ["board", "post_number"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PostCalendarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "event_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the CalendarEvent. Stored as integer soft-ref (no FK).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The board post associated with this calendar event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to="evennia_boards.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented per parent object."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full snapshot of the content at this version."
                    ),
                ),
                (
                    "editor_name",
                    models.CharField(
                        help_text="Denormalized name of the editor for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_rollback",
                    models.BooleanField(
                        default=False,
                        help_text="True if this version was created by a rollback operation.",
                    ),
                ),
                (
                    "rolled_back_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If is_rollback, the version number that was restored.",
                        null=True,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="The character who made this edit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="evennia_boards.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Updated after each login notification sweep. Posts created after this timestamp count as unread for the next login.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evennia_board_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="evennia_boards.board",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["board", "created_at"], name="evennia_boa_board_i_81dfc1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("board", "post_number")},
        ),
        migrations.AlterUniqueTogether(
            name="postcalendarlink",
            unique_together={("post", "event_id")},
        ),
        migrations.AlterUniqueTogether(
            name="postversion",
            unique_together={("parent", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("account", "board")},
        ),
    ]
