# Generated by Django 6.0.9 on 2026-10-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "__first__"),
        ("evennia_rptracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpsession",
            name="account_id_snapshot",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rpsession",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="comms.channeldb",
            ),
        ),
        migrations.AddField(
            model_name="rpsession",
            name="channel_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rpsession",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rpsession",
            name="source_type",
            field=models.CharField(
                choices=[("rp_session", "Room RP"), ("rp_channel_session", "Channel RP")],
                db_index=True,
                default="rp_session",
                max_length=24,
            ),
        ),
    ]
