# Generated by Django 6.0.7 on 2026-08-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name of the archiver for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique region name. Case-insensitive uniqueness enforced at the command layer.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description shown in region listings and the web compendium (max 1000 chars).",
                        max_length=1000,
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who archived this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the region.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "room_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized room name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the room's primary region for scalar readers.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The region this room belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="evennia_regions.region",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="The room. A room may belong to multiple regions.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("room",),
                        name="evennia_regions_one_primary_per_room",
                    )
                ],
            },
        ),
    ]
