# Generated by Django 6.0.7 on 2026-08-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evennia_regions", "0001_initial"),
        ("objects", "__first__"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="regionmembership",
            unique_together={("region", "room")},
        ),
    ]
