# Generated by Django 6.0.7 on 2026-10-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.SlugField(max_length=80)),
                ('terrains', models.JSONField(blank=True, default=list)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('in_trickle', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'key'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='resources_positive_weight')],
            },
        ),
        migrations.CreateModel(
            name='ResourceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('source', models.CharField(choices=[('trickle', 'Trickle'), ('payout', 'Payout'), ('exchange', 'Exchange'), ('craft', 'Craft'), ('staff', 'Staff')], max_length=16)),
                ('week', models.CharField(blank=True, db_index=True, max_length=80)),
                ('session_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('thread_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('exchange_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evennia_rp_resources.resourcedefinition')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resource__isnull', True), ('source', 'trickle')), fields=('character', 'week'), name='resources_one_batch_receipt'), models.CheckConstraint(condition=models.Q(('resource__isnull', False), models.Q(('quantity', 0), ('source', 'trickle')), _connector='OR'), name='resources_receipt_or_resource')],
            },
        ),
        migrations.CreateModel(
            name='ResourceHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evennia_rp_resources.resourcedefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'resource'), name='resources_one_holding'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='resources_nonnegative_holding')],
            },
        ),
    ]
