# Generated by Django 6.0.9 on 2026-10-10 18:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('template', 'Template'), ('unique', 'Unique')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('short_desc', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(max_length=200)),
                ('stat_block', models.JSONField(default=dict)),
                ('abilities', models.JSONField(default=list)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NPCCombatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_policy', models.CharField(default='random', max_length=100)),
                ('action_weights', models.JSONField(default=dict)),
                ('special_moves', models.JSONField(default=list)),
                ('reaction_policy', models.JSONField(default=dict)),
                ('boss_check_schedule', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_profile', to='evennia_npcs.npcblueprint')),
            ],
        ),
        migrations.CreateModel(
            name='NPCPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('owner', 'Owner'), ('player', 'Player')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='evennia_npcs.npcblueprint')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='NPCPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('auto_approved', 'Auto-approved')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='evennia_npcs.npcblueprint')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='NPCSpawnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawned_object_name', models.CharField(max_length=200)),
                ('spawner_name', models.CharField(max_length=200)),
                ('controller_name', models.CharField(blank=True, max_length=200)),
                ('room_id_snapshot', models.PositiveIntegerField(null=True)),
                ('spawned_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField()),
                ('despawned_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spawns', to='evennia_npcs.npcblueprint')),
                ('controller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('spawned_object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('spawner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
                ('unique_blueprint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evennia_npcs.npcblueprint')),
            ],
            options={
                'ordering': ['-spawned_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NPCSceneAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='evennia_npcs.npcspawnrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PlotNPCLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.PositiveIntegerField()),
                ('linked_by_id_snapshot', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_links', to='evennia_npcs.npcblueprint')),
            ],
        ),
        migrations.AddConstraint(
            model_name='npcblueprint',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='npcs_name_casefold'),
        ),
        migrations.AddConstraint(
            model_name='npcpermission',
            constraint=models.UniqueConstraint(fields=('blueprint', 'holder'), name='npcs_permission_holder'),
        ),
        migrations.AddConstraint(
            model_name='npcpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'owner')), fields=('blueprint',), name='npcs_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='npcpermissionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('blueprint', 'requester'), name='npcs_pending_request'),
        ),
        migrations.AddConstraint(
            model_name='npcsceneappearance',
            constraint=models.UniqueConstraint(fields=('spawn', 'scene_id'), name='npcs_spawn_scene'),
        ),
        migrations.AddConstraint(
            model_name='plotnpclink',
            constraint=models.UniqueConstraint(fields=('blueprint', 'thread_id'), name='npcs_blueprint_thread'),
        ),
    ]
