# Generated by Django 6.0.7 on 2026-10-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=24)),
                ('from_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('to_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('from_accounts', models.JSONField(default=list)),
                ('to_accounts', models.JSONField(default=list)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('fee', models.PositiveBigIntegerField(default=0)),
                ('fee_kind', models.CharField(blank=True, max_length=24)),
                ('assets', models.JSONField(default=list)),
                ('exchange_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('listing_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give', models.JSONField(default=list)),
                ('want', models.JSONField(default=list)),
                ('secret', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(db_index=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_offers_sent', to='objects.objectdb')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_offers_received', to='objects.objectdb')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_offers_here', to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='Purse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='economy_nonnegative_balance')],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('first_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_flags', to='evennia_economy.ledgerentry')),
                ('second_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_flags', to='evennia_economy.ledgerentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('first_entry', 'second_entry'), name='economy_one_roundtrip_flag')],
            },
        ),
        migrations.CreateModel(
            name='StipendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('starting', 'Starting'), ('reveal', 'Reveal')], max_length=16)),
                ('amount', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'kind'), name='economy_one_stipend')],
            },
        ),
        migrations.CreateModel(
            name='UBIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=80)),
                ('amount', models.PositiveBigIntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'week'), name='economy_one_ubi_period')],
            },
        ),
    ]
