# Generated by Django 6.0.9 on 2026-10-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_economy', '0001_initial'),
        ('objects', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewflag',
            name='event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='kind',
            field=models.CharField(default='round_trip', max_length=24),
        ),
        migrations.AlterField(
            model_name='reviewflag',
            name='first_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_flags', to='evennia_economy.ledgerentry'),
        ),
        migrations.AlterField(
            model_name='reviewflag',
            name='second_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_flags', to='evennia_economy.ledgerentry'),
        ),
        migrations.CreateModel(
            name='DroppedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_id', models.PositiveBigIntegerField()),
                ('giver_name', models.CharField(max_length=255)),
                ('accounts', models.JSONField(default=list)),
                ('room_id', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stall', 'Stall'), ('shop', 'Shop')], default='stall', max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('slot', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('last_active', models.DateTimeField()),
                ('upkeep_period', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('holding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='economy_stock', to='objects.objectdb')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economy_stores', to='objects.objectdb')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economy_markets', to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.JSONField(default=list)),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('returned', 'Returned')], db_index=True, default='active', max_length=8)),
                ('buyer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='evennia_economy.storefront')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storefront',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('room', 'slot'), name='economy_open_stall_slot'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='economy_positive_listing_price'),
        ),
    ]
