# Generated by Django 6.0.3 on 2026-06-02 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoreTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Tag name. Case-insensitive uniqueness enforced at the command layer.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_major",
                    models.BooleanField(
                        default=False,
                        help_text="Major tags are staff-defined. Minor tags are player-created.",
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the tag.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_major", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized name of the archiver for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "entry_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented globally. Used as the human-readable entry ID.",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Entry title. Unique among PUBLISHED entries (partial unique constraint).",
                        max_length=255,
                    ),
                ),
                ("body", models.TextField(blank=True, help_text="Full article body.")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short teaser shown in listings and as the hint for RESTRICTED entries.",
                        max_length=500,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized author name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[("public", "Public"), ("restricted", "Restricted")],
                        db_index=True,
                        default="public",
                        max_length=12,
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when a player has flagged this entry for staff review.",
                    ),
                ),
                ("flag_reason", models.CharField(blank=True, max_length=500)),
                ("flagged_by_name", models.CharField(blank=True, max_length=255)),
                ("reviewed_by_name", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who archived this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who authored the entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who flagged the entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "objects_tagged",
                    models.ManyToManyField(
                        blank=True,
                        help_text="In-game items or equipment associated with this lore entry.",
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who approved or rejected the entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific rooms this lore entry is associated with.",
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="entries", to="evennia_lore.loretag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoreVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented per parent object."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full snapshot of the content at this version."
                    ),
                ),
                (
                    "editor_name",
                    models.CharField(
                        help_text="Denormalized name of the editor for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_rollback",
                    models.BooleanField(
                        default=False,
                        help_text="True if this version was created by a rollback operation.",
                    ),
                ),
                (
                    "rolled_back_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If is_rollback, the version number that was restored.",
                        null=True,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="The character who made this edit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="evennia_lore.loreentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlotLoreLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "thread_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the PlotThread linked to this lore entry.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The lore entry linked to this plot thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_links",
                        to="evennia_lore.loreentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoreAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name.",
                        max_length=255,
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("passive", "Passive"),
                            ("shared", "Shared"),
                            ("storyteller", "Storyteller"),
                            ("seed", "Seed"),
                        ],
                        db_index=True,
                        default="passive",
                        max_length=12,
                    ),
                ),
                (
                    "session_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="PK of the RPSession that triggered this acquisition (PASSIVE only). Integer soft-reference — no DB cascade on session deletion.",
                        null=True,
                    ),
                ),
                ("shared_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character who acquired the entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who shared this entry via +share (SHARED only).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The lore entry that was acquired.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisitions",
                        to="evennia_lore.loreentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquired_at"],
                "unique_together": {("entry", "character")},
            },
        ),
        migrations.CreateModel(
            name="LoreRegionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "region_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the Region associated with this lore entry.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The lore entry associated with this region.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_links",
                        to="evennia_lore.loreentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "unique_together": {("entry", "region_id")},
            },
        ),
        migrations.CreateModel(
            name="LoreSceneLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "scene_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the Scene linked to this lore entry.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The lore entry linked to this scene.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_links",
                        to="evennia_lore.loreentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "unique_together": {("entry", "scene_id")},
            },
        ),
        migrations.AddConstraint(
            model_name="loreentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("title",),
                name="evennia_lore_title_published_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loreversion",
            unique_together={("parent", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="plotlorelink",
            unique_together={("thread_id", "entry")},
        ),
    ]
