# Generated by Django 6.0.3 on 2026-06-26 18:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Tag name. Case-insensitive uniqueness enforced at the command layer.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_major",
                    models.BooleanField(
                        default=False,
                        help_text="Major tags are staff-defined. Minor tags are player-created.",
                    ),
                ),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the tag.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_major", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlotArc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arc_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented globally. Used as the human-readable arc ID.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief tagline. Evolving narrative detail lives in PlotUpdate blocks.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                ("creator_name", models.CharField(blank=True, max_length=255)),
                (
                    "arc_type",
                    models.CharField(
                        choices=[("story", "Story"), ("downtime", "Downtime")],
                        db_index=True,
                        default="story",
                        max_length=12,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one arc may be current at a time (partial unique constraint).",
                    ),
                ),
                (
                    "xp_mult_rp_session",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="XP multiplier for RP session awards. Blank = type default.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "xp_mult_cutscene",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="XP multiplier for cutscene post awards. Blank = type default.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "xp_mult_lore",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="XP multiplier for lore contribution awards. Blank = type default.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "xp_mult_thread_bonus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="XP multiplier for plot-thread conclusion bonus. Blank = type default.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "xp_mult_rp_channel_session",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="XP multiplier for IC-channel session awards. Blank = type default.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created the arc.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="arcs", to="evennia_plots.plottag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlotThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plot_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented globally. Used as the human-readable thread ID.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief tagline. Evolving narrative detail lives in PlotUpdate blocks.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=12,
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("invite_only", "Invite-Only"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=12,
                    ),
                ),
                ("creator_name", models.CharField(blank=True, max_length=255)),
                (
                    "hook_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Staff-visible record of +hook calls targeting this thread.",
                    ),
                ),
                (
                    "bonus_xp_computed",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Computed at conclusion (0–5). Distributed by the XP batch.",
                    ),
                ),
                (
                    "bonus_xp_awarded",
                    models.BooleanField(
                        default=False,
                        help_text="Flipped to True after the XP batch distributes the bonus.",
                    ),
                ),
                (
                    "bonus_xp_flag_reason",
                    models.CharField(
                        blank=True,
                        help_text="Set by anti-gaming sweep when thread was concluded too quickly.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent arc (staff-assigned).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threads",
                        to="evennia_plots.plotarc",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who created the thread.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "invited_characters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters explicitly invited to link content (invite_only threads).",
                        related_name="evennia_plots_invites",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="threads", to="evennia_plots.plottag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlotParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=255)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="PlotCalendarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "event_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the CalendarEvent linked to this plot thread.",
                    ),
                ),
                (
                    "advance_notice_met",
                    models.BooleanField(
                        default=False,
                        help_text="True if the event was scheduled 7+ days after this link was created. Evaluated at link-creation time; used for the +3 XP bonus.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_links",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlotBonusCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ObjectDB pk of the character who receives the bonus credit.",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The PlotThread that generated this bonus credit.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_credits",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlotBoardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "post_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the board Post linked to this plot thread.",
                    ),
                ),
                (
                    "is_ic_post",
                    models.BooleanField(
                        default=False,
                        help_text="True if the linked post belonged to an IC-type board at link-creation time. Used by _compute_bonus_xp() to award the +1 cutscene bonus.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_links",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlotUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[("ic", "IC"), ("ooc", "OOC")],
                        default="ic",
                        max_length=3,
                    ),
                ),
                ("content", models.TextField()),
                ("author_name", models.CharField(blank=True, max_length=255)),
                (
                    "block_number",
                    models.PositiveSmallIntegerField(
                        help_text="Sequential per thread or arc. Used in edit commands."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="evennia_plots.plotarc",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlotUpdateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented per parent object."
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full snapshot of the content at this version."
                    ),
                ),
                (
                    "editor_name",
                    models.CharField(
                        help_text="Denormalized name of the editor for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_rollback",
                    models.BooleanField(
                        default=False,
                        help_text="True if this version was created by a rollback operation.",
                    ),
                ),
                (
                    "rolled_back_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If is_rollback, the version number that was restored.",
                        null=True,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="The character who made this edit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="evennia_plots.plotupdate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScenePlotLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "scene_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="PK of the Scene linked to this plot thread.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character who created the link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_links",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("sequel", "Sequel"), ("related", "Related")],
                        default="related",
                        max_length=8,
                    ),
                ),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="True for sequel links (immediate) or accepted related links.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "from_thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="evennia_plots.plotthread",
                    ),
                ),
                (
                    "to_thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="evennia_plots.plotthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="plotarc",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="evennia_plots_plotarc_one_current_global",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plotparticipant",
            unique_together={("thread", "character")},
        ),
        migrations.AlterUniqueTogether(
            name="plotcalendarlink",
            unique_together={("thread", "event_id")},
        ),
        migrations.AlterUniqueTogether(
            name="plotbonuscredit",
            unique_together={("thread", "character_id")},
        ),
        migrations.AlterUniqueTogether(
            name="plotboardlink",
            unique_together={("thread", "post_id")},
        ),
        migrations.AlterUniqueTogether(
            name="plotupdateversion",
            unique_together={("parent", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="sceneplotlink",
            unique_together={("scene_id", "thread")},
        ),
        migrations.AlterUniqueTogether(
            name="threadlink",
            unique_together={("from_thread", "to_thread")},
        ),
    ]
