# Generated by Django 6.0.3 on 2026-06-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incremented globally. Used as the human-readable ticket ID.",
                        unique=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("request", "Request"),
                            ("bug", "Bug"),
                            ("issue", "Issue"),
                            ("discuss", "Discuss"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("answered", "Answered"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized author name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "assignee_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized assignee name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when status transitions to Closed.",
                        null=True,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member assigned to handle this ticket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who submitted this ticket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized author name for display after deletion.",
                        max_length=255,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_staff_only",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this comment is hidden from the ticket submitter.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="evennia_jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="evennia_job_status_673458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "status"], name="evennia_job_job_typ_94cb0f_idx"
            ),
        ),
    ]
