# Generated by Django 6.0.3 on 2026-06-25 00:00 (hand-crafted — standalone env cannot
# load Evennia typeclasses without a full game dir; kept byte-for-byte identical to
# what makemigrations would emit given the models.py definitions in this package).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
    ]

    operations = [
        # ---------------------------------------------------------------
        # EventTag
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation of when to apply this tag.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        # ---------------------------------------------------------------
        # EventCluster
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="EventCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Once True, no events can be added/removed. The cluster "
                            "lottery draw is armed and will run at the earliest member "
                            "event's 72h draw window."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who created this cluster.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        # ---------------------------------------------------------------
        # CalendarEvent
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Event start time, stored in UTC.",
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized creator name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "participant_cap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum confirmed attendees. Null = unlimited (open mode).",
                        null=True,
                    ),
                ),
                (
                    "emphasis",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("skill", "Skill"),
                            ("social", "Social"),
                            ("freeform", "Freeform"),
                        ],
                        default="freeform",
                        max_length=10,
                    ),
                ),
                (
                    "is_staff_event",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If True, uses lottery RSVP mode. Staff characters cannot "
                            "pre-invite participants (anti-favoritism enforcement)."
                        ),
                    ),
                ),
                (
                    "lottery_drawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Set when the lottery draw runs (72h before scheduled_time). "
                            "Used as an idempotency guard — scheduler no-ops if set."
                        ),
                        null=True,
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, db_index=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "If set, this event is part of a ranked-choice cluster. "
                            "Direct RSVP is blocked; players use +rsvp/cluster."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="evennia_calendar.eventcluster",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character who scheduled this event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="evennia_calendar.eventtag",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["scheduled_time", "is_cancelled"],
                name="evennia_cal_schedul_88a4a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["is_staff_event", "is_cancelled"],
                name="evennia_cal_is_staf_0d06c6_idx",
            ),
        ),
        # ---------------------------------------------------------------
        # ClusterRSVP
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="ClusterRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("seated", "Seated"),
                            ("unseated", "Unseated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_rsvps",
                        to="evennia_calendar.eventcluster",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="clusterrsvp",
            unique_together={("cluster", "character")},
        ),
        # ---------------------------------------------------------------
        # ClusterRSVPPreference
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="ClusterRSVPPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        help_text="1 = most preferred. Must be unique per ClusterRSVP.",
                    ),
                ),
                (
                    "cluster_rsvp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="evennia_calendar.clusterrsvp",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="clusterrsvppreference",
            unique_together={("cluster_rsvp", "event"), ("cluster_rsvp", "rank")},
        ),
        # ---------------------------------------------------------------
        # RSVP
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("invited", "Invited"),
                            ("lottery_entered", "Lottery Entered"),
                            ("lottery_selected", "Lottery Selected"),
                            ("released", "Released"),
                        ],
                        db_index=True,
                        default="lottery_entered",
                        max_length=20,
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ordering for WAITLISTED RSVPs. Lower = higher priority.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "cluster_rsvp",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "For clustered events: back-link to the ClusterRSVP ticket "
                            "that produced this concrete RSVP row."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concrete_rsvps",
                        to="evennia_calendar.clusterrsvp",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
            ],
            options={
                "ordering": ["event", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rsvp",
            index=models.Index(
                fields=["event", "status"],
                name="evennia_cal_event_i_8f9dc5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rsvp",
            unique_together={("event", "character")},
        ),
        # ---------------------------------------------------------------
        # PriorityToken
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="PriorityToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("cluster_rank1", "Cluster Rank-1"),
                        ],
                        default="event",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the token is consumed at draw time.",
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "redeemed_cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cluster where this token was consumed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_redeemed",
                        to="evennia_calendar.eventcluster",
                    ),
                ),
                (
                    "redeemed_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event where this token was consumed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_redeemed",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
                (
                    "source_cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cluster that issued this token (cluster lottery).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_issued",
                        to="evennia_calendar.eventcluster",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff event that issued this token (standalone lottery).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_issued",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prioritytoken",
            index=models.Index(
                fields=["character", "redeemed_at"],
                name="evennia_cal_charact_2a7f93_idx",
            ),
        ),
        # ---------------------------------------------------------------
        # EventExclusion
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name="EventExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "event_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions_as_a",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
                (
                    "event_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions_as_b",
                        to="evennia_calendar.calendarevent",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="eventexclusion",
            unique_together={("event_a", "event_b")},
        ),
    ]
