# Generated by Django 6.0.3 on 2026-06-03 02:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.PositiveIntegerField(
                        help_text="ObjectDB pk of the character. One row per character.",
                        unique=True,
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after object deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Lifetime XP earned (sum of all XPLog rows for this character).",
                        max_digits=10,
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Lifetime XP spent on abilities/upgrades.",
                        max_digits=10,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Spendable XP remaining: total_earned - total_spent.",
                        max_digits=10,
                    ),
                ),
                (
                    "last_payout_week",
                    models.CharField(
                        blank=True,
                        help_text="ISO week of the most recent batch that awarded XP to this character.",
                        max_length=10,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this row was updated."
                    ),
                ),
            ],
            options={
                "verbose_name": "Character XP",
                "verbose_name_plural": "Character XP",
                "ordering": ["-total_earned"],
            },
        ),
        migrations.CreateModel(
            name="XPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="ObjectDB pk of the character who received this XP.",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for display after object deletion.",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="XP awarded (Decimal to support 0.5 inspiration amounts).",
                        max_digits=6,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rp_session", "RP Session"),
                            ("lore_authored", "Lore Authored"),
                            ("lore_inspiration", "Lore Inspiration"),
                            ("cutscene", "Cutscene"),
                            ("thread_bonus", "Thread Bonus"),
                            ("arc_bonus", "Arc Bonus"),
                            ("manual_grant", "Manual Grant"),
                            ("rp_channel_session", "RP Channel Session"),
                        ],
                        db_index=True,
                        help_text="Category of activity that earned this XP.",
                        max_length=22,
                    ),
                ),
                (
                    "source_ref_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="PK of the upstream item (RPSession, LoreEntry, Post, etc.). Set to own pk for MANUAL_GRANT entries.",
                    ),
                ),
                (
                    "week",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ISO week when this XP was awarded, e.g. '2026-W18'.",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-readable description (required for MANUAL_GRANT).",
                        max_length=500,
                    ),
                ),
                (
                    "multiplier_applied",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="The XP multiplier that was active when this row was written.",
                        max_digits=5,
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this XP row was written."
                    ),
                ),
                (
                    "granted_by_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ObjectDB pk of the staff member who issued a MANUAL_GRANT.",
                        null=True,
                    ),
                ),
                (
                    "granted_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized staff name for display after deletion.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["character_id", "week"],
                        name="evennia_xp__charact_1ffdda_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("source_type", "manual_grant"), _negated=True
                        ),
                        fields=("source_type", "source_ref_id"),
                        name="evennia_xp_xplog_non_manual_source_unique",
                    )
                ],
            },
        ),
    ]
