# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, an0n-b1nary. See LICENSE for full terms.
# Generated by Django 6.0.3 on 2026-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_xp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.PositiveIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=64)),
                ('ref_key', models.CharField(max_length=128, unique=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_by_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
