# Generated by Django 6.0.9 on 2026-10-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicheDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('behaviours', models.JSONField(default=list)),
                ('input_categories', models.JSONField(default=list)),
                ('unlock_money', models.PositiveBigIntegerField(default=100)),
                ('unlock_resources', models.JSONField(default=dict)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CraftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafter_id', models.PositiveBigIntegerField(db_index=True)),
                ('crafter_name', models.CharField(max_length=255)),
                ('crafter_accounts', models.JSONField(default=list)),
                ('niche_name', models.CharField(max_length=120)),
                ('behaviour', models.SlugField(max_length=80)),
                ('item_id', models.PositiveBigIntegerField(unique=True)),
                ('resources_spent', models.JSONField(default=dict)),
                ('money_spent', models.PositiveBigIntegerField(default=0)),
                ('prose', models.JSONField(default=dict)),
                ('hallmark', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evennia_rp_crafting.nichedefinition')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_money', models.PositiveBigIntegerField(default=0)),
                ('last_craft', models.DateTimeField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='objects.objectdb')),
            ],
        ),
        migrations.CreateModel(
            name='NicheUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('money_paid', models.PositiveBigIntegerField(default=0)),
                ('resources_paid', models.JSONField(default=dict)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evennia_rp_crafting.nichedefinition')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='evennia_rp_crafting.workshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('abandoned_at__isnull', True)), fields=('workshop', 'niche'), name='crafting_one_active_niche')],
            },
        ),
        migrations.CreateModel(
            name='WorkshopInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_key', models.SlugField(max_length=80)),
                ('quantity', models.PositiveBigIntegerField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='evennia_rp_crafting.workshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workshop', 'resource_key'), name='crafting_one_investment')],
            },
        ),
    ]
