# Generated by Django 6.0.9 on 2026-10-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_rp_crafting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRoomLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveBigIntegerField(unique=True)),
                ('last_used', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(max_length=255)),
                ('room_id', models.PositiveBigIntegerField()),
                ('destinations', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('craft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evennia_rp_crafting.craftrecord')),
            ],
        ),
    ]
