# Generated by Django 6.0.7 on 2026-10-03 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized character name for staff listings.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("approved", "Approved"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "allocation_spent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Allocation points spent, for allocations that count points.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character this sheet belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rp_build",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff account that last approved or reopened the sheet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "character build",
                "ordering": ["character_name"],
            },
        ),
    ]
