# Generated by Django 6.0.7 on 2026-10-03 02:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_rp_chargen', '0001_initial'),
        ('objects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbuild',
            name='allowance_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='starting_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="This sheet's starting allowance; empty means RP_CHARGEN_STARTING_ALLOWANCE.", max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='AbilityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by_name', models.CharField(blank=True, help_text='Denormalized name of the archiver for display after deletion.', max_length=255)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.SlugField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_flaw', models.BooleanField(default=False)),
                ('acquisition', models.CharField(choices=[('xp', 'Bought with XP'), ('staff', 'Staff grant only'), ('free', 'Free, self-service')], default='xp', max_length=8)),
                ('xp_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('max_level', models.PositiveSmallIntegerField(default=1)),
                ('budget_cost', models.PositiveIntegerField(default=0, help_text='Loadout budget used while equipped.')),
                ('tag_kind', models.SlugField(blank=True, help_text="Template: each copy names a tag of this kind, written '@tag' in effects.", max_length=32)),
                ('effects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='The character who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AbilityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.PositiveIntegerField(db_index=True)),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('ability_name', models.CharField(blank=True, max_length=255)),
                ('tag_key', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('acquire', 'Acquired'), ('upgrade', 'Upgraded'), ('grant', 'Granted by staff'), ('revoke', 'Revoked by staff'), ('flaw_add', 'Flaw taken'), ('flaw_remove', 'Flaw removed'), ('allowance', 'Allowance set')], max_length=12)),
                ('level_from', models.PositiveSmallIntegerField(default=0)),
                ('level_to', models.PositiveSmallIntegerField(default=0)),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Starting allowance spent (negative: refunded).', max_digits=8)),
                ('xp_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='XP spent through the ledger (negative: refunded).', max_digits=8)),
                ('ledger_ref', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='evennia_rp_chargen.abilitydefinition')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by_name', models.CharField(blank=True, help_text='Denormalized name of the archiver for display after deletion.', max_length=255)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.SlugField(default='domain', max_length=32)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='The character who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectdb')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evennia_rp_chargen.abilitydefinition')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_abilities', to='objects.objectdb')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evennia_rp_chargen.tagdefinition')),
            ],
            options={
                'verbose_name_plural': 'character abilities',
                'constraints': [models.UniqueConstraint(condition=models.Q(('tag__isnull', False)), fields=('character', 'ability', 'tag'), name='rp_chargen_one_copy_per_tag'), models.UniqueConstraint(condition=models.Q(('tag__isnull', True)), fields=('character', 'ability'), name='rp_chargen_one_copy')],
            },
        ),
    ]
