# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, an0n-b1nary. See LICENSE for full terms.
# Generated by Django 6.0.7 on 2026-10-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_rp_chargen', '0002_abilities_and_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitydefinition',
            name='budget_cost_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Template tag keys mapped to loadout costs; other tags use budget_cost.'),
        ),
    ]
